from fastapi import APIRouter, Depends, HTTPException, status
from app.core.ids import ObjectId
from app.database import get_database
from app.dependencies import get_current_user
from app.services.risk_scoring import compute_scan_risk

router = APIRouter()

@router.get("/scans/{scan_id}")
async def get_scan_risk_explanation(scan_id: str, current_user: dict = Depends(get_current_user)):
    db = get_database()
    try:
        obj_id = ObjectId(scan_id)
    except:
        raise HTTPException(status_code=400, detail="Invalid scan ID")
        
    scan = await db.scans.find_one({"_id": obj_id, "owner_id": str(current_user["_id"])})
    if not scan:
        raise HTTPException(status_code=404, detail="Scan not found")
        
    if scan.get("status") != "completed":
        raise HTTPException(status_code=400, detail="Risk score not available yet. Scan must be completed.")
        
    # We must fetch the actual vulnerabilities generated by this scan
    vulns = await db.vulnerabilities.find({"scan_id": scan_id}).to_list(length=1000)
    
    score_data = compute_scan_risk(vulns)
    return score_data
