version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: vulnai-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: 
      context: ./backend
    container_name: vulnai-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - SECRET_KEY=vulnai_super_secret_for_docker
    depends_on:
      - mongodb

  frontend:
    build: 
      context: .
    container_name: vulnai-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
